name: actions

on:
  push:
    paths: ['Dockerfile']

jobs:
  Docker-Build-Release:
    if: ${{ github.ref == 'refs/heads/main' }}  # 检测main分支是否有更新
    runs-on: ubuntu-latest
    steps:
    - name: 获取当前日期
      id: date
      run: echo "::set-output name=date::$(date +v%Y.%m.%d)"
    - uses: actions/checkout@v2 # pull代码到运行服务器上
    - name: 登录阿里云仓库
      uses: aliyun/acr-login@v1 # 使用阿里云镜像服务action
      with:
        login-server: registry.cn-hangzhou.aliyuncs.com # 务必正确填写镜像容器服务的登录地址
        region-id: cn-hangzhou # 务必正确填写镜像容器服务的登录地址
        username: "${{ secrets.REGISTRY_USERNAME }}" # 引用GitHub repo设置的镜像容器服务用户名
        password: "${{ secrets.REGISTRY_PASSWORD }}" # 引用GitHub repo设置的镜像容器服务密码
    - name: 构建和上传Docker镜像
      env:
        IMAGE_TAG: ${{ steps.date.outputs.date }}-action # 用于标记容器版本号
      run: |
        docker build -t registry.cn-hangzhou.aliyuncs.com/joybo/ant-media-server:$IMAGE_TAG .
        docker push registry.cn-hangzhou.aliyuncs.com/joybo/ant-media-server:$IMAGE_TAG
